### PR TITLE
Picto filter

### PR DESCRIPTION
**Pull request by frodrigo**
Allow to switch icon to picto as option in place of just hide.

### CODE REVIEW

**Comment by GuillaumeAmat** [comment]
@frodrigo tell me if you want a new release

**Comment by frodrigo** [comment]
Yes, we need a new release now.

**Comment by GuillaumeAmat** [comment]
Done, v0.5.0 is out.

**Comment by frodrigo** [comment]
Thank.
I need to deploy the style to get the demo working.

**Comment by GuillaumeAmat** [comment]
Ok, I'm on it.

**Comment by frodrigo** [comment]
Now it works.

**Pull request merged**
