### PR TITLE
Fix icon/picto switch with new poi layer

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by frodrigo** [comment]
@GuillaumeAmat Hello, I am not able to write this in TS.

This part is not valid
```js
f (!expr || !expr[4] || expr[4][0] !== 'case' || expr[4][1] !== 'let') {
```

Not sure if it come from my code or the type definition.

```
(typescript) Error: /home/fred/work/teritorio/teritorio-maps/src/poiFilter.ts(188,28): semantic error TS7053: Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'string | number | true | MapboxExpr'.
  Property '0' does not exist on type 'string | number | true | MapboxExpr'.
```

**Comment by GuillaumeAmat** [comment]
> @GuillaumeAmat Hello, I am not able to write this in TS.
> 
> This part is not valid
> 
> ```js
> f (!expr || !expr[4] || expr[4][0] !== 'case' || expr[4][1] !== 'let') {
> ```
> 
> Not sure if it come from my code or the type definition.
> 
> ```
> (typescript) Error: /home/fred/work/teritorio/teritorio-maps/src/poiFilter.ts(188,28): semantic error TS7053: Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'string | number | true | MapboxExpr'.
>   Property '0' does not exist on type 'string | number | true | MapboxExpr'.
> ```

It's fixed in the commit I just pushed. You just had to check that the variable is an array before using it as an array. To avoid breakage if the variable is a string or anything else.

**Comment by frodrigo** [comment]
> It's fixed in the commit I just pushed. You just had to check that the variable is an array before using it as an array. To avoid breakage if the variable is a string or anything else.

Got it. Thank you.

**Comment by frodrigo** [comment]
@GuillaumeAmat please can you release a new 0.6.0 version with this?

**Comment by GuillaumeAmat** [comment]
> @GuillaumeAmat please can you release a new 0.6.0 version with this?

Sure 👌

**Comment by GuillaumeAmat** [comment]
Done

**Pull request merged**
